### ISSUE TITLE
Wrong passphrase error

### ISSUE THREAD

**Issue by wiemann** [scastiel/protonmail-export#5]
protonmail-export can't decrypt my private key. It's a OpenPGP.js v2.5.3 key. 
The error I get is "Wrong passphrase error" even though I can log on to the web interface with the exact same key without any issues.

Any idea?

**Comment by wiemann** [comment]
Oh, seems like they changed to the algo to hashed passwords.

**Comment by ghost** [comment]
@wiemann Could you elaborate on the "hashed passwords"? Which hash are they using for this?

**Comment by wiemann** [comment]
They now use a salt for the password. It's in the attribute "KeySalt" of the /auth response. You need to look at the code to see how they process it. But the protonmail-export library does not work anymore when utilizing the procedure described in the project readme.

**Comment by ghost** [comment]
@wiemann Got it, thanks.

**Comment by ghost** [comment]
https://github.com/ProtonMail/WebClient/blob/public/src/app/authentication/services/passwords.js#L29

Is where the hashing happens. Wouldn't be able to figure this out for the life of me using node; don't know what packages would do the trick.

**Comment by dexice** [comment]
Hello 

I made a little script here : https://github.com/dexice/pmpkpe
You should be able to recover the passphrase based on the MailBoxPassword and SaltKey
